In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Data processing

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [7]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [9]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

## Feature selection

In [10]:
X = dataset.iloc[:, 3: 13].values

In [11]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [13]:
y = dataset.iloc[:, 13].values

In [14]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

## categorical encoding

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [15]:
#Label encoder for 'country', 1 is the index of 'country' col
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [18]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [19]:
from sklearn.preprocessing import OneHotEncoder

## One-hot encoding

In [20]:
#One-hot encoding 'country' col
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\kx764qe\AppData\Roaming\Python\Python37\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\kx764qe\AppData\Roaming\Python\Python37\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [21]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [22]:
X = X[:, 1:]

## data split

In [23]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

In [24]:

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.2, random_state = 0)


In [25]:
from sklearn.preprocessing import StandardScaler

## Feature scaling

In [26]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Model building

In [27]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

Using TensorFlow backend.
C:\Users\kx764qe\AppData\Local\Continuum\anaconda3\envs\courses\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\kx764qe\AppData\Local\Continuum\anaconda3\envs\courses\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\kx764qe\AppData\Local\Continuum\anaconda3\envs\courses\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 =

In [28]:
#initialize the nerual network
classifier = Sequential()

In [29]:
#add input layer and first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
#add dropout layer
classifier.add(Dropout(p =0.1))
#add 2nd hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dropout(p =0.1))
#add output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))




Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


C:\Users\kx764qe\AppData\Local\Continuum\anaconda3\envs\courses\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  
C:\Users\kx764qe\AppData\Local\Continuum\anaconda3\envs\courses\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  after removing the cwd from sys.path.
C:\Users\kx764qe\AppData\Local\Continuum\anaconda3\envs\courses\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
C:\Users\kx764qe\AppData\Local\Continuum\anaconda3\envs\courses\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  import sys
C:\Users\kx764qe\AppData\Local\Continuum\anaconda3\envs\courses\lib\site-packages\ipykernel

# compile the model

In [30]:
classifier.compile(optimizer = 'Adam', loss ='binary_crossentropy', metrics = ['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


# Fit the model

In [31]:

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 3s 361us/step - loss: 0.5130 - acc: 0.7955
Epoch 2/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.4328 - acc: 0.8101
Epoch 3/100
8000/8000 [==============================] - 2s 219us/step - loss: 0.4219 - acc: 0.8205
Epoch 4/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.4212 - acc: 0.8165
Epoch 5/100
8000/8000 [==============================] - 2s 287us/step - loss: 0.4191 - acc: 0.8195
Epoch 6/100
8000/8000 [==============================] - 2s 218us/step - loss: 0.4150 - acc: 0.8187
Epoch 7/100
8000/8000 [==============================] - 2s 239us/step - loss: 0.4114 - acc: 0.8226
Epoch 8/100
8000/8000 [==============================] - 3s 321us/step - loss: 0.4089 - acc: 0.8199
Epoch 9/100
8000/8000 [==============================] - 2s 240us/step - loss: 0.4105 - acc: 0.8212
Epoch 10/100
8000/8000 [==============================] - 2s 271us/step - loss: 0.4117 - acc: 0.8204

8000/8000 [==============================] - 2s 243us/step - loss: 0.3891 - acc: 0.8395
Epoch 81/100
8000/8000 [==============================] - 2s 238us/step - loss: 0.3887 - acc: 0.8386
Epoch 82/100
8000/8000 [==============================] - 2s 249us/step - loss: 0.3921 - acc: 0.8366
Epoch 83/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.3874 - acc: 0.8361
Epoch 84/100
8000/8000 [==============================] - 2s 228us/step - loss: 0.3883 - acc: 0.8379
Epoch 85/100
8000/8000 [==============================] - 2s 234us/step - loss: 0.3912 - acc: 0.8370
Epoch 86/100
8000/8000 [==============================] - 2s 300us/step - loss: 0.3925 - acc: 0.8389
Epoch 87/100
8000/8000 [==============================] - 2s 253us/step - loss: 0.3950 - acc: 0.8361
Epoch 88/100
8000/8000 [==============================] - 3s 386us/step - loss: 0.3874 - acc: 0.8385 2s - loss: 0.3768  - ETA: 2
Epoch 89/100
8000/8000 [==============================] - 2s 288us/step - lo

# model preciting

In [35]:

y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [36]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [37]:
cm

array([[1547,   48],
       [ 234,  171]], dtype=int64)